import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const today = new Date();

  return (
    <div>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Marksheet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="section">
          <div className="container">
            {today.toLocaleDateString()}
            <table className="table-auto">
              <thead>
                <tr>
                  <th className="border px-4 py-2">Part1</th>
                  <th className="border px-4 py-2">Part2</th>
                  <th className="border px-4 py-2">Part3</th>
                  <th className="border px-4 py-2">Part4</th>
                  <th className="border px-4 py-2">Listening計</th>
                  <th className="border px-4 py-2">Part5</th>
                  <th className="border px-4 py-2">Part6</th>
                  <th className="border px-4 py-2">Part7</th>
                  <th className="border px-4 py-2">Reading計</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border px-4 py-2">/6</td>
                  <td className="border px-4 py-2">/25</td>
                  <td className="border px-4 py-2">/39</td>
                  <td className="border px-4 py-2">/30</td>
                  <td className="border px-4 py-2">/100</td>
                  <td className="border px-4 py-2">/30</td>
                  <td className="border px-4 py-2">/16</td>
                  <td className="border px-4 py-2">/54</td>
                  <td className="border px-4 py-2">/100</td>
                </tr>
              </tbody>
            </table>
            <table className="table is-bordered">
              <thead>
                <tr>
                  <th className="border px-4 py-2">Part1</th>
                  <th className="border px-4 py-2">Part2</th>
                  <th className="border px-4 py-2">Part3</th>
                  <th className="border px-4 py-2">Part4</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border px-4 py-2">
                    <div>
                      <input type="radio" name="mark_1" id="mark_1_a"></input>
                      <label className="mark_label" htmlFor="mark_1_a">
                        <span>A</span>
                      </label>
                      <input type="radio" name="mark_1" id="mark_1_b"></input>
                      <label className="mark_label" htmlFor="mark_1_b">
                        <span>B</span>
                      </label>
                      <input type="radio" name="mark_1" id="mark_1_c"></input>
                      <label className="mark_label" htmlFor="mark_1_c">
                        <span>C</span>
                      </label>
                      <input type="radio" name="mark_1" id="mark_1_d"></input>
                      <label className="mark_label" htmlFor="mark_1_d">
                        <span>D</span>
                      </label>
                    </div>
                  </td>
                </tr>
                <tr>
                  <td className="border px-4 py-2">
                    <div>
                      <input type="radio" name="mark_1" id="a"></input>
                      <label className="mark_label" htmlFor="a">
                        <span>A</span>
                      </label>
                      <input type="radio" name="mark_1" id="b"></input>
                      <label className="mark_label" htmlFor="b">
                        <span>B</span>
                      </label>
                      <input type="radio" name="mark_1" id="c"></input>
                      <label className="mark_label" htmlFor="c">
                        <span>C</span>
                      </label>
                      <input type="radio" name="mark_1" id="d"></input>
                      <label className="mark_label" htmlFor="d">
                        <span>D</span>
                      </label>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
            <table className="table is-bordered">
              <thead>
                <tr>
                  <th className="border px-4 py-2">Part5</th>
                  <th className="border px-4 py-2">Part6</th>
                  <th className="border px-4 py-2">Part7</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border px-4 py-2">
                    <div>
                      <input type="radio" name="mark_1" id="a"></input>
                      <label className="mark_label" htmlFor="a">
                        <span>A</span>
                      </label>
                      <input type="radio" name="mark_1" id="b"></input>
                      <label className="mark_label" htmlFor="b">
                        <span>B</span>
                      </label>
                      <input type="radio" name="mark_1" id="c"></input>
                      <label className="mark_label" htmlFor="c">
                        <span>C</span>
                      </label>
                      <input type="radio" name="mark_1" id="d"></input>
                      <label className="mark_label" htmlFor="d">
                        <span>D</span>
                      </label>
                    </div>
                  </td>
                </tr>
                <tr>
                  <td className="border px-4 py-2">
                    <div>
                      <input type="radio" name="mark_1" id="a"></input>
                      <label className="mark_label" htmlFor="a">
                        <span>A</span>
                      </label>
                      <input type="radio" name="mark_1" id="b"></input>
                      <label className="mark_label" htmlFor="b">
                        <span>B</span>
                      </label>
                      <input type="radio" name="mark_1" id="c"></input>
                      <label className="mark_label" htmlFor="c">
                        <span>C</span>
                      </label>
                      <input type="radio" name="mark_1" id="d"></input>
                      <label className="mark_label" htmlFor="d">
                        <span>D</span>
                      </label>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
